django_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("inventoryManager.urls")),
    path('admin/', admin.site.urls),
]

inventoryManager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('accessDenied', views.denied, name='denied'),

    path('createUser/', views.CreateUser, name = 'create-user'),
    path('login/', views.LoginUser, name = 'login-user'),
    path('logout/', views.LogoutUser, name = 'logout-user'),
    path('user/', views.UserDetails, name = 'user-details'),

    path('organizations/', views.OrganizationListView, name = 'organizations'),
    path('organization/<int:id>', views.OrganizationDetailView, name='organization-detail'),
    path('createOrganization/', views.CreateOrganization, name='create-organization'),
    path('editOrganization/<int:id>', views.EditOrganization, name='edit-organization'),
    path('deleteOrganization/<int:id>', views.DeleteOrganization, name='delete-organization'),

    path('organization/<int:id>/createOrder', views.OrganizationCreateOrder, name = 'create-order'),
    path('organization/<int:orgId>/editOrder/<int:orderId>', views.OrganizationEditOrder, name = 'edit-order'),
    path('organization/<int:orgId>/deleteOrder/<int:orderId>', views.OrganizationDeleteOrder, name = 'delete-order'),
    path('organization/<int:organizationId>/orders/<int:orderId>', views.OrderDetailView, name='order-detail'),

    path('organization/<int:organizationId>/orders/<int:orderId>/item/<int:itemId>', views.OrderItemDetail, name='order-item-detail'),
    path('organization/<int:organizationId>/orders/<int:orderId>/createOrderItem', views.CreateOrderItem, name='create-order-item'),
    path('organization/<int:organizationId>/orders/<int:orderId>/editItem/<int:itemId>', views.EditOrderItem, name='edit-order-item'),
    path('organization/<int:orgId>/orders/<int:orderId>/deleteItem/<int:itemId>', views.DeleteOrderItem, name='delete-order-item'),
]

inventoryManager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

# Highest level, the organization
# An organization will have multiple orders
class Organization(models.Model):
    name = models.CharField(max_length = 200, unique = True)
    about = models.CharField(max_length = 200, blank = True)
    associatedUser = models.ForeignKey(User, on_delete=models.CASCADE, default = None)

    # Define the default string to return the name that represents the Model object.
    def __str__(self):
        return self.name

    # Returns the URL to access a particular instance of MyModelName.
    # Defining the method causes Django to automagically add a
    # "View on Site" button to the model's record editing screen
    # In the Admin site.
    def get_absolute_url(self):
        return reverse('organization-detail', args=[str(self.id)])

    def getNumOrders(self):
        return Order.objects.filter(organization = self).count()

# An order object
# An order is assigned to only one organization
# but an order can have many line-items
class Order(models.Model):
    title = models.CharField(max_length = 200)
    description = models.CharField(max_length = 200)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, default = None)

    posted = models.DateField()
    ordered = models.DateField(blank = True, null=True)
    completed = models.DateField(blank = True, null=True)

    # Define the default string to return the name that represents the Model object.
    def __str__(self):
        return self.title

    # Returns the URL to access a particular instance of MyModelName.
    # Defining the method causes Django to automagically add a
    # "View on Site" button to the model's record editing screen
    # In the Admin site.
    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

    def getNumItems(self):
        return OrderItem.objects.filter(order = self).count()

    def getTotalCost(self):
        allOrderItems = OrderItem.objects.filter(order = self)
        totalCost = 0.00

        for item in allOrderItems:
            totalCost += item.getTotalCost()

        return totalCost

class OrderItem(models.Model):
    itemName = models.CharField(max_length = 200)
    itemNsn = models.CharField(max_length = 200)
    itemQuantity = models.DecimalField(max_digits=5, decimal_places=0)
    itemCost = models.DecimalField(max_digits=12, decimal_places=2)

    order = models.ForeignKey(Order, on_delete=models.CASCADE, default = None)

    def get_absolute_url(self):
        return reverse('order-item-detail', args=[str(self.order.organization.id), str(self.order.id), str(self.id)])

    def getTotalCost(self):
        return float(self.itemQuantity) * float(self.itemCost)

inventoryManager/forms.py
from django import forms
from datetime import datetime
from django.forms import ModelForm

from inventoryManager.models import *

# Define the forms below
class DateInput(forms.DateInput):
    input_type = 'date'

class OrganizationForm(forms.Form):
    name = forms.CharField(label = "Organization name:", max_length=32)
    about = forms.CharField(label = "Description:", max_length=128, required=False)

class OrderForm(forms.Form):
    posted = forms.DateField(widget=DateInput)
    ordered = forms.DateField(widget=DateInput, required=False)
    completed = forms.DateField(widget=DateInput, required=False)

    title = forms.CharField(max_length = 200)
    description = forms.CharField(max_length = 200, required=False)

class UserCreateForm(forms.Form):
    username = forms.CharField(max_length = 200)
    password = forms.CharField(max_length = 200)
    email = forms.CharField(max_length = 200)
    first_name = forms.CharField(max_length = 200)
    last_name = forms.CharField(max_length = 200)

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length = 200)
    password = forms.CharField(max_length = 200)

class UserChangePasswordForm(forms.Form):
    oldPassword = forms.CharField(max_length = 200)
    password = forms.CharField(max_length = 200)

class OrderItemForm(forms.Form):
    itemName = forms.CharField(max_length = 200)
    itemNsn = forms.CharField(max_length = 200)
    itemQuantity = forms.DecimalField(max_digits=5, decimal_places=0)
    itemCost = forms.DecimalField(max_digits=12, decimal_places=2)

inventoryManager/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views import generic
from inventoryManager.models import *
from django.http import HttpResponse
from inventoryManager.forms import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

def userAuthCheck(user, expectedUser):
    if request.user.is_authenticated and organization.associatedUser == request.user:
        # User's logged in, so we get their object. we also check if this is their organization
        # and let them in
        return True
    elif request.user.is_authenticated and organization.associatedUser != request.user:
        # this isn't the user's organization. okay at this point whoever keeps fucking with stuff
        # needs to get a life. unless we hired that one to poke.
        return render(request, 'inventoryManager/denied.html')
    else:
        # user's anonymous, so we can't let them continue
        # let them know by bringing them to the login page.
        return redirect('login-user')

# Create your views here.
def index(request):
    organizations = Organization.objects.all()
    context = {'organizations':organizations}

    # user authenticated specific stuff
    if request.user.is_authenticated:
        # User's logged in, go get their username
        # also, we want the template to be slightly different, but that's on the template side
        context['currentuser'] = request.user
    else:
        # user's anonymous, so we don't have to do anything
        # some placeholder stuff is here in case we want to tinker with anonymous access later
        1+1

    return render( request, 'inventoryManager/index.html', context)

def denied(request):
    return render(request, 'inventoryManager/denied.html')

# ///////////////////////////////////////////////
# //         BEGIN USER SPECIFIC STUFF         /////////////////////////////////////////////////////////////
# ///////////////////////////////////////////////

# Method to create a user
def CreateUser(request):
    form = UserCreateForm()

    if (request.method == 'POST'):
        if request.POST['submit'] == "Cancel":
            return redirect('index')
        elif request.POST['submit'] == "Submit":
            # Get form data and verify
            form = UserCreateForm(request.POST.copy())
            if form.is_valid():
               #clean the form data and assign it to something we can use
               data = form.cleaned_data
               
               #create new object from data
               newUser = User(
                   username = data['username'],
                   email = data['email'],
                   first_name = data['first_name'],
                   last_name = data['last_name'],
                   )
               #have to use a separate method to set a user's password
               # simply setting it as part of the create user object won't work
               #because the password has to be made a hash.
               # https://www.reddit.com/r/django/comments/xwy9uw/authenticate_method_of_djangocontribauth/
               newUser.set_password(data['password'])

               #commit new object to database
               newUser.save()

               # Redirect back to the organizations list page
               return redirect('index')

    context = {'form': form}
    context['state'] = "Create"
    return render(request, 'inventoryManager/create_user_form.html', context)

#View method for a user to login
def LoginUser(request):
    form = UserLoginForm()
    context = {'state' : "Login"}
    context['form'] =  form

    if (request.method == 'POST'):
        if request.POST['submit'] == "Cancel":
            return redirect('index')
        elif request.POST['submit'] == "Submit":
            # Get form data and verify
            form = UserLoginForm(request.POST.copy())
            if form.is_valid():
               #clean the form data and assign it to something we can use
               data = form.cleaned_data
               username = data['username']
               password = data['password']
               
               # get submitted details and try to authenticate
               user = authenticate(username=username, password=password)

               if user is not None:
                   # user entered good data
                   login(request, user)
                   return redirect('index')
               else:
                   #User entered some bad data
                   form = UserLoginForm(
                       initial={
                           "username" : data['username'],
                           }
                       )
                   context['form'] =  form
                   return render(request, 'inventoryManager/user_login_form.html', context)

    return render(request, 'inventoryManager/user_login_form.html', context)

def LogoutUser(request):
    logout(request)
    return redirect('index')

def UserDetails(request):
    context = {}

    # user authenticated specific stuff
    if request.user.is_authenticated:
        # User's logged in, so we get their object
        # and let them in
        context['currentuser'] = request.user
    else:
        # user's anonymous, so we can't show them a user page
        # let them know by bringing them to the login page.
        return redirect('login-user')

    context = {"currentuser" : request.user}
    return render(request, 'inventoryManager/user_details.html', context)

# ///////////////////////////////////////////////
# //       END OF USER SPECIFIC STUFF          /////////////////////////////////////////////////////////////
# ///////////////////////////////////////////////

# ///////////////////////////////////////////////
# //     BEGIN ORGANIZATION SPECIFIC STUFF     /////////////////////////////////////////////////////////////
# ///////////////////////////////////////////////

# Method to create an organization
def CreateOrganization(request):
    form = OrganizationForm()
    context = {}

    # user authenticated specific stuff
    if request.user.is_authenticated:
        # User's logged in, so we get their object
        # and let them in
        context['currentuser'] = request.user
    else:
        # user's anonymous, so we can't let them make an organization
        # let them know by bringing them to the login page.
        return redirect('login-user')

    if (request.method == 'POST'):
        if request.POST['submit'] == "Cancel":
            return redirect('organizations')
        elif request.POST['submit'] == "Submit":
            # Get form data and verify
            form = OrganizationForm(request.POST.copy())
            if form.is_valid():
               #clean the form data and assign it to something we can use
               data = form.cleaned_data
               
               #create new object from data
               newOrganization = Organization(
                   name = data['name'],
                   about = data['about'],
                   associatedUser = request.user
                   )

               #commit new object to database
               newOrganization.save()

               # Redirect back to the organizations list page
               return redirect('organizations')

    context['form'] = form
    context['state'] = "Create"
    return render(request, 'inventoryManager/organization_form.html', context)

# Method to edit an organization
def EditOrganization(request, id):
    organizationToUpdate = Organization.objects.get(pk=id)
    context = {'organization' : organizationToUpdate}

    # user authenticated specific stuff
    if request.user.is_authenticated and organizationToUpdate.associatedUser == request.user:
        # User's logged in, so we get their object. we also check if this is their organization
        # and let them in
        context['currentuser'] = request.user
        context['allow'] = 'yes'
    elif request.user.is_authenticated and organizationToUpdate.associatedUser != request.user:
        # this isn't the user's organization. can't let them do poking now can we?
        # don't let them edit anything and redirect to permission denied page since they probably
        # poked around to get here
        context['currentuser'] = request.user
        return render(request, 'inventoryManager/denied.html')
    else:
        # user's anonymous, so we can't let them continue
        # let them know by bringing them to the login page.
        return redirect('login-user')

    # Populate the form with the organization's current data
    form = OrganizationForm(
        initial={"name" : organizationToUpdate.name,
                 "about" : organizationToUpdate.about
                 }
        )

    if (request.method == 'POST'):
        if request.POST['submit'] == "Cancel":
            return redirect('organization-detail', id)
        elif request.POST['submit'] == "Submit":
            # Get form data and verify
            form = OrganizationForm(request.POST.copy())
            if form.is_valid():
               #clean the form data and assign it to something we can use
               data = form.cleaned_data
               
               #create new object from data
               organizationToUpdate.name = data['name']
               organizationToUpdate.about = data['about']

               #commit new object to database
               organizationToUpdate.save()

               # Redirect back to the organizations list page
               return redirect('organizations')

    context['form'] = form
    context['state'] = "Edit"
    return render(request, 'inventoryManager/organization_form.html', context)

# Method to delete an organization
def DeleteOrganization(request, id):
    # Get the data for the project to delete
    organizationToDelete = Organization.objects.get(id=id)
    context = {"organization" : organizationToDelete,

inventoryManager/templates/inventoryManager/denied.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <title>CXR Inventory Management</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'scripts/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'scripts/jquery-2.2.4.js' %"></script>
    <script src="{% static 'scripts/color-modes.js' %}"></script>
</head>

<body>
    <h1>Access denied.</h1>
    <p>You do not have access to perform that action.</p>
</body>
</html>

inventoryManager/templates/inventoryManager/index.html
<!-- inherit from base.html-->
{% extends "inventoryManager/base_template.html" %}
{% load static %}

<!-- Replace block content in base_template.html -->
{% block content %}
<h1 class="display-4 mx-2">Inventory Management Project</h1>
{% if currentuser %}
    <h1 class="display-6 mx-2">Welcome, {{ currentuser.username }}</h1>
{% endif %}
<h1 class="display-6 mx-4">Organizations managed:</h1>
    {% if organizations %}
    <div class="container d-flex flex-row p-1 text-dark text-left float-start d-grid gap-3 mx-4">
        {% for i in organizations %}
        <div class="card" style="width: 20rem;">
	        <img class="card-img-top" src="{% static 'images/noImage.png' %}" alt="Organization Logo">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <p class="card-text">
                    <strong>POC: </strong><br />{{ i.associatedUser.last_name }}, {{ i.associatedUser.first_name }}<br />
                    <strong>Contact Email: </strong><br />{{ i.associatedUser.email }}
                </p>
                <a class="btn btn-primary" href="{{ i.get_absolute_url }}" role="button">View</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="lead text-warning">There are no registered organizations.</p>
    {% endif %}
{% endblock %}

inventoryManager/templates/inventoryManager/item_delete.html
<!-- inherit from base.html -->
{% extends 'inventoryManager/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a> ->
            <a href="{% url 'order-detail' organization.id order.id %}">{{ order.title }}</a> ->
            {% if item_data %}
            {{ state }}: <a href="{% url 'order-item-detail' organization.id order.id item_data.id %}">{{ item_data.itemName }}</a>
            {% else %}
            {{ state }}: Order Item
            {% endif %}
        </h1>
    </div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    <strong>Are you sure you want to delete this item?</strong>
    <!-- <input formnovalidate class="btn btn-primary" type="submit" value="Cancel" name="submit"> -->
    <a href="{% url 'order-item-detail' organization.id order.id item_data.id %}" type="button" class="btn btn-primary">Cancel</a>
    <input class="btn btn-primary" type="submit" value="Delete" name="submit">
</form>

{% endblock %}

inventoryManager/templates/inventoryManager/item_detail.html
{% extends 'inventoryManager/base_template.html' %}

{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a> ->
            <a href="{% url 'order-detail' organization.id order.id %}">{{ order.title }}</a> ->
            {{ orderItem.itemName }}
        </h1>
    </div>
</div>

    <a class="btn btn-secondary" href="{% url 'edit-order-item' organization.id order.id orderItem.id %}" role="button">Edit Details</a>
{% endblock %}

inventoryManager/templates/inventoryManager/order_delete.html
<!-- inherit from base.html -->
{% extends 'inventoryManager/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a> ->
            {% if order %}
            {{ state }}: <a href="{% url 'order-detail' organization.id order.id %}">{{ order.title }}</a>
            {% else %}
            {{ state }} Order
            {% endif %}
        </h1>
    </div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    <strong>Are you sure you want to delete this order?</strong>
    <p>This order has: {{ order.getNumItems }} items.</p>
    <!-- <input formnovalidate class="btn btn-primary" type="submit" value="Cancel" name="submit"> -->
    <a href="{% url 'order-detail' organization.id order.id %}" type="button" class="btn btn-primary">Cancel</a>
    <input class="btn btn-primary" type="submit" value="Delete" name="submit">
</form>

{% endblock %}

inventoryManager/templates/inventoryManager/order_form.html
<!-- inherit from base.html -->
{% extends 'inventoryManager/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a> ->
            {% if order %}
            {{ state }}: <a href="{% url 'order-detail' organization.id order.id %}">{{ order.title }}</a>
            {% else %}
            {{ state }}: Order
            {% endif %}
        </h1>
    </div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label class="control-label lead" for="id_{{ field.name }}">{{ field.label }}</label>
        <br>
        {{ field }}
        <br>
    </div>
    {% endfor %}

    <!-- <input formnovalidate class="btn btn-primary" type="submit" value="Cancel" name="submit"> -->
    {% if order %}
    <a href="{% url 'order-detail' organization.id order.id %}" type="button" class="btn btn-primary">Cancel</a>
    {% else %}
    <a href="{% url 'organization-detail' organization.id %}" type="button" class="btn btn-primary">Cancel</a>
    {% endif %}
    <input class="btn btn-primary" type="submit" value="Submit" name="submit">
</form>

{% endblock %}

inventoryManager/templates/inventoryManager/order_item_form.html
<!-- inherit from base.html -->
{% extends 'inventoryManager/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a> ->
            <a href="{% url 'order-detail' organization.id order.id %}">{{ order.title }}</a> ->
            {% if item_data %}
            {{ state }}: <a href="{% url 'order-item-detail' organization.id order.id item_data.id %}">{{ item_data.itemName }}</a>
            {% else %}
            {{ state }}: Order Item
            {% endif %}
        </h1>
    </div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label class="control-label lead" for="id_{{ field.name }}">{{ field.label }}</label>
        <br>
        {{ field }}
        <br>
    </div>
    {% endfor %}
    {% if item_data %}
    <a href="{% url 'order-item-detail' organization.id order.id item_data.id %}" type="button" class="btn btn-primary">Cancel</a>
    {% else %}
    <a href="{% url 'order-detail' organization.id order.id %}" type="button" class="btn btn-primary">Cancel</a>
    {% endif %}
    <input class="btn btn-primary" type="submit" value="Submit" name="submit">
</form>

{% endblock %}

inventoryManager/templates/inventoryManager/organization_delete.html
<!-- inherit from base.html -->
{% extends 'inventoryManager/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            {% if organization %}
            {{ state }}: <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a>
            {% else %}
            {{ state }}: Organization
            {% endif %}
        </h1>
    </div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    <strong>Are you sure you want to delete this organization?</strong>
    <p></p>
    <input class="btn btn-primary" type="submit" value="Cancel" name="submit">
    <input class="btn btn-primary" type="submit" value="Delete" name="submit">
</form>

{% endblock %}

inventoryManager/templates/inventoryManager/organization_detail.html
{% extends 'inventoryManager/base_template.html' %}
{% load static %}

{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            {{ organization.name }}
        </h1>
    </div>
</div>

<div class="d-flex flex-column d-grid gap-4 mx-2 mb-4">
    <div class="d-flex flex-row">
        <!-- Image container-->
        <img src="{% static 'images/noImage.png' %}" alt="Organization Logo">

        <!-- Content Container-->
        <div>
            <h5 class="">
                <strong>POC:  </strong>{{ organization.associatedUser.last_name }}, {{ organization.associatedUser.first_name }}
            </h5>
            <h5 class="">
                <strong>Contact Email:  </strong>{{ organization.associatedUser.email }}
            </h5>
            <h5 class="">
                <strong>About: </strong> {{ organization.about }}
            </h5>

            {% if allow %}
            <!-- Only show edit options if a user is logged in and this is their organization-->
            <a class="btn btn-secondary" href="{% url 'edit-organization' organization.id %}" role="button">Edit Details</a>
            <a class="btn btn-danger" href="{% url 'delete-organization' organization.id %}" role="button">Delete</a>
            {% endif %}
        </div>
    </div>
</div>

{% if order_list %}
<div class="mx-2">
    {% if allow %}
    <h2>List of Orders: <a class="btn btn-primary" href="{% url 'create-order' organization.id %}" role="button">New</a></h2>
    {% else %}
    <h2>List of Orders: </h2>
    {% endif %}
</div>
<div class="container d-flex flex-row p-1 text-dark text-left float-start mx-4">

    {% for order in order_list %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5>{{ order.title }}</h5>
            <p class="card-text">{{ order.description }}</p>
            <p class="card-text">Items in order: {{ order.getNumItems }}</p>
            <p class="card-text">Order Cost: ${{ order.getTotalCost }}</p>

            {% if currentuser %}
            <!-- only let a user see the order details if logged in.-->
            <a class="btn btn-primary" href="{% url 'order-detail' organization.id order.id %}" role="button">View</a>
            <a class="btn btn-secondary" href="{% url 'edit-order' organization.id order.id %}" role="button">Edit Details</a>
            <a class="btn btn-danger" href="{% url 'delete-order' organization.id order.id %}" role="button">Delete</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
        {% else %}
            {% if allow %}
                <h2>This organization has no orders.<a class="btn btn-primary" href="{% url 'create-order' organization.id %}" role="button">New</a></h2>
            {% else %}
                <h2>This organization has no orders.</h2>
            {% endif %}
        {% endif %}
    {% endblock %}

inventoryManager/templates/inventoryManager/organization_form.html
<!-- inherit from base.html -->
{% extends 'inventoryManager/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="d-flex flex-column d-grid gap-4 mb-4">
    <div class="d-flex flex-row border gap-4 mx-2">
        <h1>
            <a href="{% url 'organizations' %}">Organizations</a> ->
            {% if organization %}
            {{ state }}: <a href="{% url 'organization-detail' organization.id %}">{{ organization.name }}</a>
            {% else %}
            {{ state }}: Organization
            {% endif %}
        </h1>

    </div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label class="control-label lead" for="id_{{ field.name }}">{{ field.label }}</label>
        <br>
        {{ field }}
        <br>
    </div>
    {% endfor %}
    <!-- <input formnovalidate class="btn btn-primary" type="submit" value="Cancel" name="submit"> -->
    {% if organization %}
    <a href="{% url 'organization-detail' organization.id %}" type="button" class="btn btn-primary">Cancel</a>
    {% else %}
    <a href="{% url 'organizations' %}" type="button" class="btn btn-primary">Cancel</a>
    {% endif %}
    <input class="btn btn-primary" type="submit" value="Submit" name="submit">
</form>

{% endblock %}

inventoryManager/templates/inventoryManager/user_details.html
{% extends 'inventoryManager/base_template.html' %}

{% block content %}
<h1>User details</h1>

<h2>My organizations:</h2>
    {% if organization_list %}
<div class="container d-flex flex-row p-1 text-dark text-left float-start">
    {% for org in organization_listt %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5>{{ org.name }}</h5>
            <p class="card-text">{{ org.description }}</p>
            <a class="btn btn-primary" href="{% url 'order-detail' organization.id order.id %}" role="button">View</a>
        </div>
    </div>
    {% endfor %}
</div>
        {% else %}
<p>This user has no organizations.</p>
    {% endif %}
    {% endblock %}